version: '3'

services:
  postgres:
    restart: always
    image: postgres:alpine
    env_file: ./.env
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
      POSTGRES_DB: $DB_NAME
    expose: 
      - "5432"
    volumes:
      - data:/var/lib/postgresql/data
      
  redis:
    container_name: redis-cache
    image: redis
    ports:
      - '6379:6379'
    expose:
      - '6379'

  node_api:
    restart: always
    build: ./node_api
    container_name: node_api
    expose: 
      - "8080"
    command: yarn start
    depends_on:
      - postgres
      - redis
    env_file: ./.env
    environment:
      - DB_HOST=postgres
      - VIRTUAL_HOST=proxy.example
    stdin_open: true
    tty: true

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    links:
      - node_api:node_api

volumes:
  data:
    external: false
 





    

    
    
  
